#!/usr/bin/env node
const properties = require('./assets/properties.json')
const index = {}
Object.keys(properties).forEach(prop => {
  index[prop] = properties[prop][0]
  index[prop].property = prop
})
console.log(JSON.stringify(index, null, 2))
