#!/usr/bin/env bash
set -eu

mkdir -p ./assets/js

echo "updating properties"
# Using the QLever engine, as query.wikidata.org tends to timeout on this query
wd sparql ./scripts/assets/properties.rq --index property --sparql-endpoint https://qlever.dev/wikidata > ./scripts/assets/properties.json

echo -en '// Generated by scripts/update_properties.sh\nexport default ' > ./assets/js/properties.js.tmp
./scripts/get_properties_index.js >> ./assets/js/properties.js.tmp

# Now that risky operations are over, we can cleanup
# with a low risk of crashing and letting empty files behind us
mv ./assets/js/properties.js.tmp ./assets/js/properties.js

echo "generating properties index"
./scripts/generate_properties_index.js

echo "copying the index in the public folder to make it publicly accessible"
cp ./assets/js/properties_index.js ./public/properties_index.js

echo "generating properties links data"
# Disable requests logs to prevent
# `RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded`
export HUB_VERBOSE_REQUESTS=false
./scripts/generate_links_data.js
