SELECT ?property ?label ?type ?urlFormat ?authority (GROUP_CONCAT(?alias;separator='\n') AS ?aliases)
WHERE {
  ?property a wikibase:Property .
  ?property wikibase:propertyType ?propertyType .
  BIND(STRAFTER(STR(?propertyType), '#') as ?type)
  OPTIONAL { ?property wdt:P1630 ?urlFormat . }
  # Not using 'SERVICE wikibase:label' to get a flat simplified object
  # and not { value, label }
  ?property rdfs:label ?label .
  FILTER((LANG(?label)) = "en")
  OPTIONAL {
    ?property skos:altLabel ?alias .
    FILTER((LANG(?alias)) = "en")
  }
  OPTIONAL {
    ?property wdt:P31/wdt:P279* wd:Q18614948 .
    BIND (TRUE AS ?authority)
  }
}
GROUP BY ?property ?label ?type ?urlFormat ?authority
ORDER BY ASC(xsd:integer(STRAFTER(STR(?property), 'P')))
